apiVersion: v1
kind: Service
metadata:
  name: static-proxy
  labels:
    service: static-proxy
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
      name: https
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: registryhttps
  selector:
    service: proxy
    release: deepsecurity-smartcheck
