apiVersion: v1
kind: Service
metadata:
  name: static-proxy
  labels:
    service: static-proxy
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: registryhttps
  selector:
    service: proxy
    release: deepsecurity-smartcheck